version: '3.1'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: dev-frontend
    ports:
      - "8085:3000"
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: prod-frontend
    ports:
      - "8090:3000"
